[pytest]
pythonpath = .
testpaths = tests
filterwarnings =
    ignore::PendingDeprecationWarning:starlette.formparsers
markers =
    postgres: mark test as requiring PostgreSQL environment or psycopg driver
